{
 "title": "by namespace",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Кіл-ть pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кіл-ть service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_service_info{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кіл-ть configmap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_configmap_info{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кіл-ть secrets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_secret_info{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кіл-ть вик. jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_job_status_succeeded{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кіл-ть невдалих job",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_job_status_failed{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase) (\n  kube_pod_status_phase{namespace=\"$namespace\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Рестарти контейнерів",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 2, "y": 3 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  kube_pod_container_status_restarts_total{namespace=\"$namespace\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Readiness/Liveness Probe Помилки",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(prober_probe_total{namespace=\"$namespace\", result=\"failed\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Читання з диску (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_fs_reads_bytes_total{namespace=\"$namespace\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Запис на диск (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_fs_writes_bytes_total{namespace=\"$namespace\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 подів по outgoing traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (pod) (\n    rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])\n  ) / 1024 / 1024\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 подів по incoming traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "topk(10,\n  sum by (pod) (\n    rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])\n  ) / 1024 / 1024\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming traffic (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(\n  rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])\n) / 1024 / 1024",
     "legendFormat": "Incoming traffic (MB/s)"
    }
   ]
  },
  {
   "title": "Outgoing traffic (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(\n  rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])\n) / 1024 / 1024",
     "legendFormat": "Outgoing traffic (MB/s)"
    }
   ]
  },
  { "title": "CPU & MEMORY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Середнє денне споживання CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(\n  avg_over_time(\n    sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\", pod!=\"\"}[5m]))[24h:]\n  )\n) * 24",
     "legendFormat": "Cpu per/hour"
    }
   ]
  },
  {
   "title": "Споживання ресурсів namespace(cpu)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "targets": [
    {
     "expr": "(\n  sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\", pod!=\"\"}[5m]))\n  /\n  sum(rate(container_cpu_usage_seconds_total{container!=\"\", pod!=\"\"}[5m]))\n) * 100",
     "legendFormat": "CPU Usage (% of cluster)"
    }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\", pod!=\"\"}[5m])\n)",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Середнє денне споживання Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(\n  avg_over_time(\n    sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", pod!=\"\"})[24h:]\n  )\n) / 1024 / 1024 / 1024 * 24",
     "legendFormat": "Memory per/hour"
    }
   ]
  },
  {
   "title": "Споживання ресурсів namespace(memory)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
   "targets": [
    {
     "expr": "(\n  sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", pod!=\"\"})\n  /\n  sum(container_memory_working_set_bytes{container!=\"\", pod!=\"\"})\n) * 100",
     "legendFormat": "CPU Usage (% of cluster)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", pod!=\"\"}\n) / 1024 / 1024 / 1024",
     "legendFormat": "Memory usage"
    }
   ]
  }
 ]
}